# Cloud Build config for backend
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.backend'
      - '-t'
      - 'us-east1-docker.pkg.dev/lifeembedding/lifeembedding-repo/backend:latest'
      - '.'

images:
  - 'us-east1-docker.pkg.dev/lifeembedding/lifeembedding-repo/backend:latest'

